# Generated by Django 5.1.1 on 2024-10-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=150, verbose_name="Ф.И.О")),
                ("comment", models.TextField()),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["full_name", "email"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=250, verbose_name="тема письма")),
                ("body_of_the_letter", models.TextField()),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщений",
                "ordering": ["subject"],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("Date_and_time_of_attempt", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(choices=[("успешно", "успешно"), ("не успешно", "не успешно")], max_length=50),
                ),
                ("Mail_server_response", models.TextField()),
                (
                    "recipients",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="newapp.mailingrecipient"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sent_date", models.DateTimeField(auto_now_add=True)),
                ("end_of_sending", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("завершена", "завершена"), ("создана", "создана"), ("запущена", "запущена")],
                        default="создана",
                        max_length=50,
                    ),
                ),
                ("message", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="newapp.message")),
                ("recipients", models.ManyToManyField(to="newapp.mailingrecipient")),
            ],
            options={
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
                "ordering": ["status", "sent_date", "end_of_sending"],
            },
        ),
    ]
