# Generated by Django 5.1.1 on 2024-11-03 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0003_mailingattempt_owner_message_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="newsletter",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="newapp.newsletter"
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="owner",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="recipients",
            field=models.ManyToManyField(to="newapp.mailingrecipient", verbose_name="Получатели"),
        ),
    ]
