# Generated by Django 5.1.1 on 2024-11-03 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0004_mailingattempt_newsletter_alter_mailingattempt_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["status", "Date_and_time_of_attempt"],
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
            },
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="Mail_server_response",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="newsletter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="newapp.newsletter"
            ),
        ),
        migrations.RemoveField(
            model_name="mailingattempt",
            name="recipients",
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="recipients",
            field=models.ManyToManyField(blank=True, to="newapp.mailingrecipient"),
        ),
    ]
