# Generated by Django 5.1.1 on 2024-11-05 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0005_alter_mailingattempt_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["status", "Date_and_time_of_attempt"],
                "permissions": [("can_view_all_mailings_attempts", "can view all mailings attempts")],
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "ordering": ["full_name", "email"],
                "permissions": [("can_view_all_recipients", "can view all recipients")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["subject"],
                "permissions": [("can_view_all_messages", "can view all messages")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщений",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["status", "sent_date", "end_of_sending"],
                "permissions": [
                    ("can_view_all_mailings", "can view all mailings"),
                    ("can_disable_mailings", "can disable mailings"),
                ],
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
            },
        ),
        migrations.AddField(
            model_name="newsletter",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserMailingStatistics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_mailings", models.PositiveIntegerField(default=0)),
                ("successful_mailings", models.PositiveIntegerField(default=0)),
                ("failed_mailings", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
