# Generated by Django 5.1.1 on 2024-11-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0006_alter_mailingattempt_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermailingstatistics",
            name="failed_mailings",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usermailingstatistics",
            name="successful_mailings",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usermailingstatistics",
            name="total_mailings",
            field=models.IntegerField(default=0),
        ),
    ]
