# Generated by Django 5.1.1 on 2024-11-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0007_alter_usermailingstatistics_failed_mailings_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "ordering": ["full_name", "email"],
                "permissions": [("can_view_all_mailingrecipient", "can view all mailingrecipient")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
