# Generated by Django 5.1.1 on 2024-11-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0008_alter_mailingrecipient_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="success",
            field=models.BooleanField(default=False),
        ),
    ]
